// <auto-generated />
using System;
using GestionGastos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionGastos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817013901_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GestionGastos.Api.Data.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_nombre_tipo");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Comida",
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Transporte",
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Vivienda",
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Servicios",
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Salud",
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Ocio",
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Otros",
                            Tipo = (byte)1
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Sueldo",
                            Tipo = (byte)2
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Ingreso extra",
                            Tipo = (byte)2
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Otros",
                            Tipo = (byte)2
                        });
                });

            modelBuilder.Entity("GestionGastos.Api.Data.Entidades.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("ARS")
                        .HasColumnName("moneda");

                    b.Property<decimal>("Monto")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("monto");

                    b.Property<string>("Nota")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("nota");

                    b.Property<byte>("Tipo")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId", "Fecha", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_movimientos_usuario_fecha_id");

                    b.ToTable("movimientos", (string)null);
                });

            modelBuilder.Entity("GestionGastos.Api.Data.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreadoEn = new DateTime(2026, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dev@gestiongastos.local"
                        });
                });

            modelBuilder.Entity("GestionGastos.Api.Data.Entidades.Movimiento", b =>
                {
                    b.HasOne("GestionGastos.Api.Data.Entidades.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_categoria");

                    b.HasOne("GestionGastos.Api.Data.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimientos_usuario");

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
